### ISSUE TITLE
Unable to find services.yaml for the qrcam integration

### ISSUE THREAD

**Issue by exxamalte** [Hypercookie/hass-qrcam#4]
## Version of the custom_component

v1.0.0.10-hotfix

## Configuration

```yaml
camera:
  - platform: qrcam
    name: "Guest WiFi"
    content: "WIFI:S:ssid;T:WPA;P:password;;"
    drawer: "rounded"
```

## Describe the bug
On startup of Home Assistant the following warning appears in the log:

```
2022-06-02 13:42:59 WARNING (SyncWorker_2) [homeassistant.helpers.service] Unable to find services.yaml for the qrcam integration
```

As suggested here https://github.com/home-assistant/core/issues/23197 the way to fix this is to add an empty `services.yaml` file.

## Debug log

n/a
